version: '3.8'

services:
  library:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8005:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  
  tests:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["pytest", "src/tests"]
    depends_on:
      - mongodb